### ISSUE TITLE
On some android 4.x fatal exception with load resources.

### ISSUE THREAD

**Issue by axti** [a-student/BetterVectorDrawable#13]
Fatal Exception: android.content.res.Resources$NotFoundException: File res/drawable-mdpi-v4/search.png from xml type xml resource ID #0x7f0200a1
       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2145)
       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2100)
       at android.content.res.Resources.getXml(Resources.java:901)
       at com.bettervectordrawable.lib.graphics.drawable.VectorDrawable.create(VectorDrawable.java:389)
       at com.bettervectordrawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:95)
       at com.bettervectordrawable.VectorDrawableFactory.get(VectorDrawableFactory.java:36)
       at com.bettervectordrawable.LongSparseArrayDrawableConstantStateWrapper.get(LongSparseArrayDrawableConstantStateWrapper.java:31)
       at com.bettervectordrawable.LongSparseArrayDrawableConstantStateWrapper.get(LongSparseArrayDrawableConstantStateWrapper.java:22)
       at com.bettervectordrawable.LongSparseArrayDrawableConstantStateWrapper.get(LongSparseArrayDrawableConstantStateWrapper.java:10)
       at android.content.res.Resources.loadDrawable(Resources.java:1881)
       at android.content.res.Resources.getDrawable(Resources.java:659)
       at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
       at android.support.v7.widget.TintManager.getDrawable(TintManager.java:147)
       at android.support.v7.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:421)
       at android.support.v7.view.menu.ActionMenuItemView.initialize(ActionMenuItemView.java:114)
       at android.support.v7.widget.ActionMenuPresenter.bindItemView(ActionMenuPresenter.java:206)
       at android.support.v7.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:182)
       at android.support.v7.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:192)
       at android.support.v7.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:451)
       at android.support.v7.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1138)
       at android.support.v7.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:91)
       at android.support.v7.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:229)
       at android.support.v7.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:284)
       at android.support.v7.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1030)
       at android.support.v7.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:1053)
       at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:449)
       at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:60)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4745)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.io.FileNotFoundException: Corrupt XML binary file
       at android.content.res.AssetManager.openXmlAssetNative(AssetManager.java)
       at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:487)
       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2127)
       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2100)
       at android.content.res.Resources.getXml(Resources.java:901)
       at com.bettervectordrawable.lib.graphics.drawable.VectorDrawable.create(VectorDrawable.java:389)
       at com.bettervectordrawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:95)
       at com.bettervectordrawable.VectorDrawableFactory.get(VectorDrawableFactory.java:36)
       at com.bettervectordrawable.LongSparseArrayDrawableConstantStateWrapper.get(LongSparseArrayDrawableConstantStateWrapper.java:31)
       at com.bettervectordrawable.LongSparseArrayDrawableConstantStateWrapper.get(LongSparseArrayDrawableConstantStateWrapper.java:22)
       at com.bettervectordrawable.LongSparseArrayDrawableConstantStateWrapper.get(LongSparseArrayDrawableConstantStateWrapper.java:10)
       at android.content.res.Resources.loadDrawable(Resources.java:1881)
       at android.content.res.Resources.getDrawable(Resources.java:659)
       at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
       at android.support.v7.widget.TintManager.getDrawable(TintManager.java:147)
       at android.support.v7.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:421)
       at android.support.v7.view.menu.ActionMenuItemView.initialize(ActionMenuItemView.java:114)
       at android.support.v7.widget.ActionMenuPresenter.bindItemView(ActionMenuPresenter.java:206)
       at android.support.v7.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:182)
       at android.support.v7.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:192)
       at android.support.v7.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:451)
       at android.support.v7.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1138)
       at android.support.v7.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:91)
       at android.support.v7.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:229)
       at android.support.v7.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:284)
       at android.support.v7.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1030)
       at android.support.v7.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:1053)
       at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:449)
       at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:60)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4745)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by a-student** [comment]
You tried to load res/drawable-mdpi-v4/search.png as vector drawable.

**Comment by axti** [comment]
This is os want load. I'm using search.xml
Declare this on my application class:  VectorDrawableCompat.enableResourceInterceptionFor(getResources(),  R.drawable.search);
And use in menu: 
 < item android:id="@+id/action_search" android:title="@string/action_search"
        android:orderInCategory="100" app:showAsAction="always" android:icon="@drawable/search" />

**Comment by a-student** [comment]
You or some lib put this image `search.png` in the `res/drawable-mdpi-v4` folder. Remove this file or (in second case) rename your `search.xml` to something else.

**Comment by axti** [comment]
I don't have res/drawable-mdpi-v4 folder.

**Comment by a-student** [comment]
Well, renaming `search.xml` should help OR update the lib, i fixed this issue recently:

```
compile 'com.bettervectordrawable:lib:0.8'
```

**Comment by a-student** [comment]
Did any of these help?

**Comment by a-student** [comment]
If you still have problems, fill free to reopen / comment.

**Comment by axti** [comment]
I changed the name, but it did not help.
Fatal Exception: android.content.res.Resources$NotFoundException: File res/drawable-mdpi-v4/search2.png from xml type xml resource ID #0x7f0200a1
search2.xml - this is new name.

**Comment by axti** [comment]
This bug on
HTC DESIRE 816G DUAL SIM
SONY C2105
SAMSUNG GT I9505
SAMSUNG GT I9295
SAMSUNG SM N910V
ONDA RMD 1035
This is on different Android versions: 4.4.4, 4.4.2, 4.2.2

**Comment by a-student** [comment]
Do you have `generatedDensities = []` line in the _defaultConfig_ section of **build.gradle**?

```
defaultConfig {
    generatedDensities = []
    …
}
```

Do you use the latest version of the lib?

```
compile 'com.bettervectordrawable:lib:0.8'
```

**Comment by axti** [comment]
Hi.
Today I tested 0.8 version. It's work. Thank you.
