### ISSUE TITLE
 parser error

### ISSUE THREAD

**Issue by ashish12s3** [a-student/BetterVectorDrawable#16]
E/VectorDrawable: parser error
                                                                         org.xmlpull.v1.XmlPullParserException: Binary XML file line #2<vector> tag requires viewportWidth > 0
                                                                             at com.bettervectordrawable.lib.graphics.drawable.VectorDrawable.updateStateFromTypedArray(VectorDrawable.java:556)
                                                                             at com.bettervectordrawable.lib.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:520)
                                                                             at com.bettervectordrawable.lib.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:531)
                                                                             at com.bettervectordrawable.lib.graphics.drawable.VectorDrawable.create(VectorDrawable.java:498)
                                                                             at com.bettervectordrawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:115)
                                                                             at com.bettervectordrawable.VectorDrawableFactory.get(VectorDrawableFactory.java:36)
                                                                             at com.bettervectordrawable.LongSparseArrayDrawableConstantStateWrapper.get(LongSparseArrayDrawableConstantStateWrapper.java:31)
                                                                             at com.bettervectordrawable.LongSparseArrayDrawableConstantStateWrapper.get(LongSparseArrayDrawableConstantStateWrapper.java:22)
                                                                             at com.bettervectordrawable.LongSparseArrayDrawableConstantStateWrapper.get(LongSparseArrayDrawableConstantStateWrapper.java:10)
                                                                             at android.content.res.Resources.loadDrawable(Resources.java:2661)
                                                                             at android.content.res.Resources.getDrawable(Resources.java:843)
                                                                             at android.content.res.Resources.getDrawable(Resources.java:818)
                                                                             at android.content.res.Resources.getDrawable(Resources.java:793)

**Comment by a-student** [comment]
Possibly you did not set `better:viewportHeight` attribute. Please, read readme.md
Did this help?

**Comment by ashish12s3** [comment]
Thank you yes I forgot to add better properties
